// Paramètres
// [x] Permission to Copy Artifact 
//      Projects to allow copy artifacts : PostfixeLib
pipeline {
    agent any
    
    environment { 
        PROJET = '~labasse/cpp/PileLib'
        ARTIFACT = 'Pile.hpp'
    }
    stages {
        stage('Init') {
            steps{
                sh "cp ${env.PROJET}/* ."
            }
        }
        stage('Build') {
            steps {
                sh 'make'
            }
        }
        stage('Test') {
            steps {
                sh 'make test'
            }
        }
    }
    post {
        success {
            archiveArtifacts artifacts: env.ARTIFACT, fingerprint: true
        }
    }
}
