pipeline {
    agent any

    parameters {
        string(name: 'WWWROOT', defaultValue: '/var/www/html', description: '')
        string(name: 'SRC', defaultValue: '~labasse/site', description: '')
    }

    stages {        
        stage('Prerequisites') {
            steps {
                sh "mkdir -p ${params.WWWROOT}/doc"
            }
        }
        stage('Build') {
            environment {
                CONV = 'pandoc'
            }
            steps {
                sh "$CONV -s ${params.SRC}/index.md -o index.html"
                
                sh "$CONV -s ${params.SRC}/index.md -o index.docx"
            }
        }
        stage('Publish') {
            steps {
                sh "mv index.html ${params.WWWROOT}"
                
                sh "mv index.docx ${params.WWWROOT}/doc"
            }
        }
    }
}
