pipeline {
    agent any

    stages {        
        stage('Prerequisites') {
            steps {
                sh "mkdir -p ${params.WWWROOT}/doc"
            }
        }
        stage('Build') {
            environment {
                CONV = 'pandoc'
            }
            parallel {
                stage('build-index') {
                    steps {
                       sh "$CONV -s ${params.SRC}/index.md -o index.html"
                       sh "$CONV -s ${params.SRC}/index.md -o index.docx"
                    }
                }
                stage('build-legal') {
                    steps {
                        sh "$CONV -s ${params.SRC}/legal.md -o legal.html"
                    }
                }
                stage('build-contact') {
                    steps {
                        sh "$CONV -s ${params.SRC}/contact.md -o contact.html"
                    }   
                }
            }
            
        }
        stage('Tests') {
            parallel {
                stage('test-index') {
                    steps {
                        sh 'tidy -qe index.html 2> test-index.txt'    
                    }
                }
                stage('test-legal') {
                    steps {
                        sh 'tidy -qe legal.html 2> test-legal.txt'    
                    }
                }
                stage('test-contact') {
                    steps {
                        sh 'tidy -qe contact.html 2> test-contact.txt'    
                    }   
                }
            }
        }
        stage('Publish') {
            steps {
                sh "cp *.html ${params.WWWROOT}"
                
                sh "cp index.docx ${params.WWWROOT}/doc"
            }
        }
    }
    post {
        success {
            writeFile file: 'test.xml', text: '''<?xml version="1.0" encoding="UTF-8"?>
                <testsuites name="Tidy" tests="1" errors="0">
                  <testsuite name="HTML" tests="1" errors="0">
                    <testcase name="HTML tidy" classname="index.html"></testcase>
                  </testsuite>
                </testsuites>'''
            junit 'test.xml'
        }
        failure {
            writeFile file: 'test.xml', text: '''<?xml version="1.0" encoding="UTF-8"?>
                <testsuites name="Tidy" tests="1" errors="1">
                  <testsuite name="HTML" tests="1" errors="1">
                    <testcase name="HTML tidy" classname="index.html">
                      <failure type="HTML"><![CDATA['''
            sh 'cat test-index.txt >> test.xml'
            sh 'cat test-legal.txt >> test.xml'
            sh 'cat test-contact.txt >> test.xml'
            sh 'echo "]]></failure></testcase></testsuite></testsuites>" >> test.xml'
            junit 'test.xml'
        }
        always {
            archiveArtifacts artifacts: '*.html, index.docx', fingerprint: true, followSymlinks: false
            emailext to: 'labasse@gmail.com', 
                attachLog: true, 
                subject: "Jenkins - ${currentBuild.fullDisplayName} : ${currentBuild.currentResult}",
                mimeType: 'text/html',
                body: "<p>Info du <a href='${env.BUILD_URL}'>build</a> :</p><ul><li>Job : ${ env.JOB_NAME }<li>N° : ${env.BUILD_NUMBER}</ul>"
        }
    }
}
